export { Reviews } from "./reviews";
export { Hero } from "./hero";
export { Benefits } from "./benefits";
export { PromoCode } from "./promo-code";
export { BeforeAfter } from "./before-after";
export { Using } from "./using";
export { Quality } from "./quality";
export { AboutProduct } from "./about-product";
export { CookieBanner } from "./cookie-banner";
